import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ToastContext from './contexts/ToastContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ToastContext />
                {children}
            </body>
        </html>
    )
}
